
#include <stdio.h>

int main() {
    // Student identification variables
    char studentName[50], regNumber[25], section[10];

    // Salary-related variables
    int empCount;
    float pay[10];
    int i, j, choice;
    float sum, mean;
    float maxPay, minPay;
    int aboveCount, belowCount;
    float swap;

    // --- Step 1: Student information input ---
    printf("******** Employee Salary Analysis ********\n");
    printf("Enter Student Name: ");
    scanf(" %[^\n]", studentName);

    printf("Enter Registration Number: ");
    scanf(" %[^\n]", regNumber);

    printf("Enter Section: ");
    scanf(" %[^\n]", section);

    // --- Step 2: Employee salary data input ---
    printf("\nHow many employees? (max 10): ");
    scanf("%d", &empCount);

    if (empCount <= 0 || empCount > 10) {
        printf("Invalid number of employees! Program terminated.\n");
        return 0;
    }

    printf("Enter the salary for each employee:\n");
    for (i = 0; i < empCount; i++) {
        printf("Employee %d: ", i + 1);
        scanf("%f", &pay[i]);
    }

    // --- Step 3: Menu operations ---
    do {
 printf("\n=============== MENU ===============\n");
 printf("1. View All Salaries\n");
 printf("2. Show Total & Average Salary\n");
 printf("3. Show Highest & Lowest Salary\n");
 printf("4. Employees Above/Below Average\n");
 printf("5. Sort Salaries (Ascending)\n");
 printf("6. Exit\n");
 printf("====================================\n");
 printf("Enter your option: ");
 scanf("%d", &choice);

 printf("\n-- Report generated by: %s | Reg: %s | Sec: %s --\n",
               studentName, regNumber, section);
printf("Challenge Day 17 – Code2Grow Program\n\n");

switch (choice) {
 case 1:
   printf("Employee Salaries:\n");
   for (i = 0; i < empCount; i++) {
   printf("Employee %d → %.2f\n", i + 1, pay[i]);
   }
   break;

 case 2:
         sum = 0;
         for (i = 0; i < empCount; i++)
         sum += pay[i];
         mean = sum / empCount;
         printf("Total Salary = %.2f\n", sum);
         printf("Average Salary = %.2f\n", mean);
       
   break;

            case 3:
                maxPay = minPay = pay[0];
                for (i = 1; i < empCount; i++) {
                    if (pay[i] > maxPay) maxPay = pay[i];
                    if (pay[i] < minPay) minPay = pay[i];
                }
                printf("Highest Salary = %.2f\n", maxPay);
                printf("Lowest Salary  = %.2f\n", minPay);
                break;

   case 4:
    sum = 0;
    for (i = 0; i < empCount; i++)
    sum += pay[i];
      mean = sum / empCount;

     aboveCount = belowCount = 0;
   for (i = 0; i < empCount; i++) {
    if (pay[i] > mean)
     aboveCount++;
   else if (pay[i] < mean)
       belowCount++;
                }

                printf("Average Salary = %.2f\n", mean);
                printf("Employees above average = %d\n", aboveCount);
                printf("Employees below average = %d\n", belowCount);
                break;

            case 5:
                // Simple bubble sort for ascending order
                for (i = 0; i < empCount - 1; i++) {
                    for (j = 0; j < empCount - i - 1; j++) {
                        if (pay[j] > pay[j + 1]) {
                            swap = pay[j];
                            pay[j] = pay[j + 1];
                            pay[j + 1] = swap ;
 }
                 
   }
               
 }

             
   printf("Salaries arranged in ascending order:\n");
            
    for (i = 0; i < empCount; i++)
         printf("%.2f ", pay[i]);
                printf("\n");
                break;

            case 6:
                printf("Thank you! Exiting the system...\n");
                break;

            default:
                printf("Invalid option! Please try again.\n");
        }

    } while (choice != 6);

    // --- Step 4: Closing message ---
    printf("\n===== End of Program =====\n");
    printf("Submitted by: %s | Reg No: %s | Section: %s\n",
           studentName, regNumber, section);
    printf("Challenge Day 17 Code2Grow Program\n");

    return 0;
}























